POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0ODcyMTVlOTE5MDY3Nzc0ZmFkMzNjNiIsImlhdCI6MTY4NjU4NDA1Nn0.ueTiMBgLGTBgP7GtJU-lojtj0jLUFRfPHQRtWL0ZxP8

{
    "title": "Blog",
    "author": "Author5",
    "url": "www.thisurldoesnotexist.com",
    "likes": 31
}